[project]
name = "resource-maxxing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colored>=2.3.0",
    "numpy>=2.2.3",
    "tk>=0.1.0",
    "torch>=2.6.0",
]
